### ISSUE TITLE
Cannot use `useTrackRenders` when component is used in the `wrapper` option

### ISSUE THREAD

**Issue by jerelmiller** [testing-library/react-render-stream-testing-library#7]
When using `renderStream.render`, I am unable to to use components that use the `useTrackRenders` hook in the `wrapper` option. As an example, see [this test](https://github.com/apollographql/apollo-client/blob/60b99d119c44a9223ef3adfabd32e23c9ca73f03/src/react/hooks/__tests__/useSuspenseQuery.test.tsx#L10649-L10660) from an Apollo Client bug that I'm working on. I'd like to move the `<Suspense />` and `<ErrorBoundary />` components to the `wrapper` option. When doing so however, I see the error:

```
useTrackRenders: A Render Stream must be created and rendered to track component renders
```

Ideally `useTrackRenders` can be used for components in the components passed to `render` and `wrapper`. This would also make it easier for more of these complex cases to use `rerender` to avoid the need to pass that whole component tree again.

**Comment by phryneas** [comment]
Good point. We probably need to swap `ParentWrapper` and `Wrapper` for that here:

https://github.com/testing-library/react-render-stream-testing-library/blob/c4b152e54c2816ae17ef35d9ccef893cf5c14ac8/src/renderStream/createRenderStream.tsx#L259-L261

**Comment by jerelmiller** [comment]
Closing as the argument against this change makes sense. Sticking with the rule of "components that track renders should be part of the test" makes a lot of sense to me and should help reduce confusion.
